image:
  repository: ghcr.io/egormak/tracker-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

config:
  mongodb:
    host: "mongo"
    port: 27017
    name: "tasker"
  telegram:
    api_key: ""
    room_id: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
