apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracker-server.fullname" . }}-config
  labels:
    {{- include "tracker-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    mongodb:
      host: {{ .Values.config.mongodb.host | quote }}
      port: {{ .Values.config.mongodb.port }}
      name: {{ .Values.config.mongodb.name | quote }}
    telegram:
      api_key: {{ .Values.config.telegram.api_key | quote }}
      room_id: {{ .Values.config.telegram.room_id | quote }}
