name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tracker-server/tracker-server:$(date +%+4Y-%m-%d)
    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - name: Push the Docker image
      run: docker push egorm/tracker-server:$(date +%+4Y-%m-%d)
      